version: "3.7"
services:
  web:
    build:
      context: .
    command: >
      bash -c "rm -f tmp/pids/* &&
      bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
      - node_modules:/myapp/node_modules
      - bundle:/myapp/vendor/bundle
      - ~/.ssh:/root/.ssh:ro
    ports:
      - "3000:3000"
      - "3035:3035"
    depends_on:
      - db
    stdin_open: true
    tty: true
  db:
    image: mysql:5.7
    volumes:
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      TZ: Asia/Tokyo
volumes:
  db_data:
  node_modules:
  bundle: